Feature/backend convert to typescript
snaanortey/foodease pull request #1
Opened 2022-11-17 15:52 UTC by snaanortey

Converted the following to typescript:
1. `get ingredients by recipes id` API
2. `image search` API that returns an array of ingredients on the image
3.  `ingredients to recipes` API that takes the ingredients array and returns recipes that match the ingredients
4. `search and suggest meals` API that takes search suggestions and returns a list of meals whose prefixes match the suggestions
5. function for populating elastic search database with the content from JSON file

2022-11-17 16:03 UTC, ehimah requested changes
This is quite good. Just some tidbits and we'd be ready to ✅

2022-11-17 16:03 UTC, ehimah commented on server/src/routes/searchAndSuggestMeals.ts
> +    const result = await elasticClient.search<ElasticSearchIndexRecipe>(query);
this logic should be abstracted into the `services/elasticClient` module.

You should create a function that takes an elastic search query as parameter, and returns the search result object as its result.

2022-11-17 16:03 UTC, ehimah commented on server/src/services/search.ts
> +
remove extra space

2022-11-17 16:03 UTC, ehimah commented on server/src/routes/getIngredientsById.ts
> +    // if err is an object of the class ResponseError
the parameter is called id not `mealId`
```suggestion
    console.log("Error getting ingredients by id", err);
    // if err is an object of the class ResponseError
```

2022-11-17 16:03 UTC, ehimah commented on server/src/index.ts
> +import getIngredientsById from "../src/routes/getIngredientsById";
remove spaces

2022-11-17 21:04 UTC, snaanortey commented on server/.gitignore
> +dist
There are no spaces as dicussed

2022-11-17 23:54 UTC, snaanortey commented on server/src/routes/imageSearch.ts
> +    const image = req.files.image as fileUpload.UploadedFile;
Addressed comment and committed changes

2022-11-17 23:58 UTC, snaanortey commented on server/src/routes/searchAndSuggestMeals.ts
> +    const result = await elasticClient.search<ElasticSearchIndexRecipe>(query);
maintained initial code as dicussed

2022-11-17 23:59 UTC, snaanortey commented on server/src/services/search.ts
> +
removed extra spaces and committed changes

2022-11-18 00:01 UTC, snaanortey commented on server/src/routes/getIngredientsById.ts
> +    // if err is an object of the class ResponseError
updated from `mealId` to `id` and committed changes

2022-11-18 00:02 UTC, snaanortey commented on server/src/index.ts
> +import getIngredientsById from "../src/routes/getIngredientsById";
removed extra spaces and committed changes

2022-11-18 00:05 UTC, snaanortey commented
Thanks for the comments! I have responded to each of your comments and created a new commit to updated changes.

2022-11-18 00:38 UTC, ehimah approved these changes

2022-11-18 00:38 UTC, merged