CAP-28 UI redesign for SearchRecipe and FullRecipe Pages
snaanortey/foodease pull request #10
Opened 2022-12-26 00:02 UTC by snaanortey

**What I did for this PR:**
- Installed and initialized next.js, tailwind, storybook
- Created the `SearchRecipes` page, temporarily the homepage - The page allows the user to search for recipes with ingredients they have, and when the user clicks the `GET RECIPES` button, the page displays `recipe summaries` that match the ingredients input.
- Created the `FullRecipe` page - The page allows the user to see the full details of a selected recipe from the `SearchIngredients` page

**Things I want to improve/ add**
- Hover effect when hovering on a recipe card in the `SearchRecipes` page
- The user to see the previously populated `SearchRecipes` page when they close the `FullRecipe` page
- Font-family to be changed to Monserrat
- On the FullRecipe page, the image is to be styled to object-fit

2022-12-26 00:09 UTC, ehimah commented on client2/README.md
> +## Getting Started
You should personalise this README file

2022-12-26 00:18 UTC, ehimah requested changes
Good job on this. Just a few comments that we need to address

2022-12-26 00:18 UTC, ehimah commented on client2/pages/api/hello.ts
> +  res.status(200).json({ name: 'John Doe' });
do we need this?

2022-12-26 00:18 UTC, ehimah commented on client2/pages/fullRecipe/index.tsx
> +              : (color = 'text-amber-800');
please add a brief comment explaining what you're doing here

2022-12-26 00:18 UTC, ehimah commented on client2/pages/index.tsx
> +        <meta name="description" content="Generated by create next app" />
can we find a better description metadata?

2022-12-26 00:18 UTC, ehimah commented on client2/pages/page.d.ts
> +};
what does this do? can you briefly explain in a few lines of comment?

2022-12-26 00:18 UTC, ehimah commented on client2/components/layouts/footer/Footer.tsx
> +export default Footer;
should there be a header layout since we have a footer layout

2022-12-26 00:18 UTC, ehimah commented on client2/.storybook/main.js
> +       */
what's the context here?

2022-12-26 00:18 UTC, ehimah commented on client2/.storybook/preview.js
> +        },
what's going on here?

2022-12-26 18:13 UTC, snaanortey commented on client2/README.md
> +## Getting Started
I have done this now

2022-12-26 18:27 UTC, snaanortey commented on client2/pages/api/hello.ts
> +  res.status(200).json({ name: 'John Doe' });
We don't need this. I have deleted it.

2022-12-26 18:33 UTC, snaanortey commented on client2/pages/fullRecipe/index.tsx
> +              : (color = 'text-amber-800');
Added a comment.

2022-12-26 18:34 UTC, snaanortey commented on client2/pages/index.tsx
> +        <meta name="description" content="Generated by create next app" />
Updated this

2022-12-26 18:54 UTC, snaanortey commented on client2/components/layouts/footer/Footer.tsx
> +export default Footer;
I have created a header layout template.

2022-12-26 18:56 UTC, snaanortey commented on client2/.storybook/main.js
> +       */
It's the documentation for dealing with storybook issues that could come from using tailwind

2022-12-26 19:06 UTC, snaanortey commented on client2/.storybook/preview.js
> +        },
This is for setting up the breakpoints I defined in the previous lines

2022-12-27 03:15 UTC, snaanortey commented on client2/pages/page.d.ts
> +};
It relates to creating persistent layouts. I put in a comment and added a link for more context.

2022-12-27 03:16 UTC, snaanortey commented
Thanks for the review and comments. I have responded individually to all comments.

2022-12-27 15:36 UTC, ehimah approved these changes

2022-12-27 15:36 UTC, ehimah commented on client2/README.md
> +
👌

2022-12-27 16:24 UTC, merged