CAP-28 Search Meals pages
snaanortey/foodease pull request #11
Opened 2022-12-28 14:03 UTC by snaanortey

Here is what I did: 

Short video of UI - https://user-images.githubusercontent.com/85527341/209823455-92cf2b15-e7bb-4a17-a74d-75162075f3b3.mov

`SearchMeal` page - Allows the user to type a meal. Populate suggestions as the user types 3 or more characters.
`ShoppingList/[mealID]` page - Provides a list of ingredients for the meal the user selects on the `SearchMeal` page

2022-12-28 23:28 UTC, ehimah requested changes
Some comments and we're good.

2022-12-28 23:28 UTC, ehimah commented on client2/pages/searchMeal/index.tsx
> +    }
what does this do?

2022-12-28 23:28 UTC, ehimah commented on client2/pages/searchMeal/index.tsx
> +      );
please bring in the backend class. all calls to your backend should be done using that `BckendClient` class

2022-12-28 23:28 UTC, ehimah commented on client2/pages/shoppingList/[recipeId].tsx
> +    .get(`http://localhost:8000/ingredients/${recipeId}`)
same here

2022-12-28 23:28 UTC, ehimah commented on client2/pages/shoppingList/[recipeId].tsx
> +  }
We need to invest in some aesthetics and best practices for loading spinners using React Suspense and/or lazy loading across the entire app.

See references https://beta.nextjs.org/docs/data-fetching/streaming-and-suspense
and https://learnjsx.com/category/4/posts/nextjs-suspense

Could you create a JIRA ticket for it and link it here?

2022-12-28 23:28 UTC, ehimah commented on client2/pages/searchMeal/index.tsx
> +    }
should this be an else?

2022-12-29 14:04 UTC, snaanortey commented on client2/pages/searchMeal/index.tsx
> +    }
fixed this

2023-01-06 15:15 UTC, snaanortey commented on client2/pages/searchMeal/index.tsx
> +      );
Done this. Included for other APIs.

2023-01-06 15:44 UTC, snaanortey commented on client2/pages/shoppingList/[recipeId].tsx
> +  }
Created the ticket [here](https://naanorkor.atlassian.net/browse/CAP-34?atlOrigin=eyJpIjoiYjZmZDUxNTg3NmVjNGNmZTg5NzU2M2UyNWE4YTNhOTAiLCJwIjoiaiJ9)

2023-01-06 15:44 UTC, snaanortey commented on client2/pages/searchMeal/index.tsx
> +    }
Updated

2023-01-06 16:05 UTC, snaanortey commented
Please re-review

2023-01-08 18:53 UTC, ehimah reviewed
a few comments to address

2023-01-08 18:53 UTC, ehimah commented on client2/pages/searchMeal/index.tsx
> +          <Link key={i} href={`/shoppingList/${meal.id}`}>
```suggestion
        {suggestedMeal.map(({id, title}, i) => (
          <Link key={i} href={`/shoppingList/${id}`}>
```

2023-01-08 18:53 UTC, ehimah commented on client2/pages/searchMeal/index.tsx
> +    }
```suggestion

    if (mealName.length < 3) {
      setSuggestedMeal([]);
      return;
    } 
    const data = await backendService.searchMealName(mealName);
      setSuggestedMeal(data);
```

2023-01-08 18:53 UTC, ehimah commented on client2/services/backend.ts
> +    this.baseUrl = 'http://localhost:8000';
We should make this configurable via constructor arguments like
```suggestion
  constructor(apiBaseUrl: string) {
    this.baseUrl = apiBaseUrl ;
```



this way we can later instantiate the class as 

```ts
const service = new BackendService('http://localhost:8000');

// or even using an environment variable
const service = new BackendService(process.env.BACKEND_API_URL);
```

2023-01-08 18:53 UTC, ehimah commented on client2/services/backend.ts
> +export const backendService = new BackendService();
this should change and the api url should be passed in

2023-01-16 17:37 UTC, snaanortey commented on client2/pages/searchMeal/index.tsx
> +          <Link key={i} href={`/shoppingList/${meal.id}`}>
👍🏾 updated this

2023-01-16 17:38 UTC, snaanortey commented on client2/pages/searchMeal/index.tsx
> +    }
👍🏾 done

2023-01-16 17:43 UTC, snaanortey commented on client2/services/backend.ts
> +    this.baseUrl = 'http://localhost:8000';
updated

2023-01-16 17:43 UTC, snaanortey commented
All comments addressed

2023-01-18 13:30 UTC, ehimah approved these changes
👌🏽

2023-01-18 14:04 UTC, merged