Cap 38 dockerize the backend
snaanortey/foodease pull request #13
Opened 2023-01-20 16:06 UTC by snaanortey

In the PR, I created a docker file and container for the backend, and migrated elastic search data to elastic cloud on kibana.

[PR ticket](https://naanorkor.atlassian.net/browse/CAP-38)

[Next PR ticket](https://naanorkor.atlassian.net/browse/CAP-40)

2023-01-22 00:07 UTC, ehimah requested changes
good job! just some more things to clean up.

2023-01-22 00:07 UTC, ehimah commented on server/src/app.ts
> +app.use(cors({credentials: true, origin: 'https://foodease-client-snaanortey.vercel.app'}));
we should store this value in an environment variable and use it here instead of being hard-coded.
When running locally, it will be `http://localhost` in your env file locally, however in vercel environment, it will be the vercel live URL 

```suggestion
app.use(cors({credentials: true, origin: 
```

2023-01-22 00:07 UTC, ehimah commented on server/src/services/elasticClient.ts
> +  process.env.ELASTIC_PASSWORD === undefined
we need a unified way of dealing with this

we should find a way to stick with the HOST URL method of connecting. Let's pair on this. see more here https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/basic-config.html

2023-01-22 00:45 UTC, snaanortey commented on client2/pages/_app.tsx
> +}
1. It's an object that defines the type of the title of each page

2. Done

2023-01-22 00:46 UTC, snaanortey commented on client2/pages/_app.tsx
> +    // <ThemeProvider>{getLayout(<Component {...props} />)}</ThemeProvider>
done

2023-01-22 00:55 UTC, snaanortey commented on server/Dockerfile
> +# Copy and download dependencies
Done

2023-01-22 00:57 UTC, snaanortey commented on server/dist/app.js
> +app.use("/image/ingredients", imageSearch_1.default);
Done

2023-01-22 01:11 UTC, snaanortey commented on server/src/app.ts
> +app.use(cors({credentials: true, origin: 'https://foodease-client-snaanortey.vercel.app'}));
👍🏾👐🏾

2023-01-22 02:02 UTC, snaanortey commented on server/src/services/elasticClient.ts
> +  process.env.ELASTIC_PASSWORD === undefined
done

2023-01-23 17:12 UTC, ehimah commented on server/src/services/elasticClient.ts
> +    throw console.error("environment variables are undefined");
```suggestion
    throw new Error("environment variables are undefined");
```

2023-01-23 17:13 UTC, ehimah commented on server/src/services/elasticClient.ts
> +  }
combine these two into one `if statement`

2023-01-23 17:13 UTC, ehimah commented on server/src/index.ts
> +export default app;
format with prettier 👁️

2023-01-23 17:14 UTC, ehimah commented on server/package.json
> +    "docker:run": "docker run -p 8000:8000 foodeaseserver"
👍🏽

2023-01-23 17:14 UTC, ehimah commented on server/package.json
> +    "start:dev": "ts-node ./src/index.ts",
maybe we don't need this anymore because it's now a duplicate of `yarn start`

2023-01-23 22:15 UTC, snaanortey commented on client2/components/searchRecipes/SearchRecipes.tsx
> +import { useRouter } from 'next/router';
done

2023-01-23 22:19 UTC, snaanortey commented on server/src/services/elasticClient.ts
> +    throw console.error("environment variables are undefined");
done

2023-01-23 22:19 UTC, snaanortey commented on server/src/services/elasticClient.ts
> +  }
done

2023-01-23 22:20 UTC, snaanortey commented on server/src/index.ts
> +export default app;
it was already formatted

2023-01-23 22:21 UTC, snaanortey commented on server/package.json
> +    "start:dev": "ts-node ./src/index.ts",
yeah. removed. but I'm wondering wth we created it.

2023-01-24 00:51 UTC, ehimah approved these changes

2023-01-24 00:53 UTC, merged